export const WHAT_WE_COVER = [
  { id: "01", title: "Python + Async Engineering", duration: "Weeks 1-3", color: "#1B4965", highlight: false },
  { id: "02", title: "LLM Mental Model", duration: "Week 4", color: "#5BC0BE", highlight: true },
  { id: "03", title: "Prompt Engineering", duration: "Weeks 5-7", color: "#7B68A6", highlight: false },
  { id: "04", title: "Ingestion Pipeline + RAG", duration: "Weeks 8-12", color: "#E85D75", highlight: false },
  { id: "05", title: "Tools, MCP & Single Agents", duration: "Weeks 13-16", color: "#7D9D7A", highlight: false },
  { id: "06", title: "Memory + Context Engineering", duration: "Weeks 17-19", color: "#E9A319", highlight: false },
  { id: "07", title: "Multi-Agent Orchestration", duration: "Weeks 20-22", color: "#C45C26", highlight: false },
  { id: "08", title: "Guardrails + LLMOps", duration: "Weeks 23-24", color: "#D4A017", highlight: false },
  { id: "09", title: "Cloud + Deployment", duration: "Weeks 25-26", color: "#1A3A5C", highlight: false },
];

export const CURRICULUM_PHASES = [
  {
    id: "01",
    chapter: "Chapter 1",
    title: "Python + Async Engineering",
    color: "#1B4965",
    lessons: 12,
    duration: "3 weeks",
    topics: [
      "Python fundamentals & type hints",
      "Async/await & asyncio patterns",
      "FastAPI for AI microservices",
      "Data structures for ML pipelines",
      "Testing & debugging AI code",
    ],
    objectives: [
      "Write production-grade async Python",
      "Build REST APIs for AI applications",
      "Structure codebases for scale",
    ],
  },
  {
    id: "02",
    chapter: "Chapter 2",
    title: "LLM Mental Model",
    color: "#5BC0BE",
    lessons: 8,
    duration: "1 week",
    topics: [
      "Transformer architecture deep dive",
      "Tokenization & embeddings",
      "Attention mechanisms explained",
      "Model families comparison",
      "Inference vs training tradeoffs",
    ],
    objectives: [
      "Understand how LLMs work internally",
      "Choose the right model for each task",
      "Reason about context windows & costs",
    ],
  },
  {
    id: "03",
    chapter: "Chapter 3",
    title: "Prompt Engineering",
    color: "#7B68A6",
    lessons: 14,
    duration: "3 weeks",
    topics: [
      "Zero-shot & few-shot prompting",
      "Chain-of-thought techniques",
      "Structured output with JSON mode",
      "Prompt templates & versioning",
      "Evaluation & iteration loops",
    ],
    objectives: [
      "Craft reliable prompts for production",
      "Build reusable prompt libraries",
      "Measure and improve prompt quality",
    ],
  },
  {
    id: "04",
    chapter: "Chapter 4",
    title: "Ingestion Pipeline + RAG",
    color: "#E85D75",
    lessons: 18,
    duration: "5 weeks",
    topics: [
      "Document chunking strategies",
      "Vector databases (Pinecone, pgvector)",
      "Embedding models & reranking",
      "Hybrid search architectures",
      "RAG evaluation frameworks",
    ],
    objectives: [
      "Build end-to-end RAG pipelines",
      "Optimize retrieval quality",
      "Deploy vector search at scale",
    ],
  },
  {
    id: "05",
    chapter: "Chapter 5",
    title: "Tools, MCP & Single Agents",
    color: "#7D9D7A",
    lessons: 16,
    duration: "4 weeks",
    topics: [
      "Function calling & tool use",
      "Model Context Protocol (MCP)",
      "Agent loop architectures",
      "ReAct & plan-and-execute patterns",
      "Building custom MCP servers",
    ],
    objectives: [
      "Build autonomous AI agents",
      "Integrate external tools via MCP",
      "Design reliable agent workflows",
    ],
  },
  {
    id: "06",
    chapter: "Chapter 6",
    title: "Memory + Context Engineering",
    color: "#E9A319",
    lessons: 10,
    duration: "3 weeks",
    topics: [
      "Short-term vs long-term memory",
      "Conversation summarization",
      "Context window management",
      "Semantic memory with vectors",
      "Memory retrieval strategies",
    ],
    objectives: [
      "Design memory systems for agents",
      "Manage context efficiently",
      "Build stateful AI applications",
    ],
  },
  {
    id: "07",
    chapter: "Chapter 7",
    title: "Multi-Agent Orchestration",
    color: "#C45C26",
    lessons: 12,
    duration: "3 weeks",
    topics: [
      "Supervisor-worker patterns",
      "Agent-to-agent communication",
      "Task decomposition strategies",
      "CrewAI & LangGraph workflows",
      "Error handling in multi-agent systems",
    ],
    objectives: [
      "Orchestrate multi-agent systems",
      "Design agent collaboration patterns",
      "Debug complex agent workflows",
    ],
  },
  {
    id: "08",
    chapter: "Chapter 8",
    title: "Guardrails + LLMOps",
    color: "#D4A017",
    lessons: 10,
    duration: "2 weeks",
    topics: [
      "Input/output guardrails",
      "Content moderation pipelines",
      "Observability & tracing",
      "Cost monitoring & optimization",
      "A/B testing LLM features",
    ],
    objectives: [
      "Deploy safe AI to production",
      "Monitor LLM performance & costs",
      "Implement CI/CD for AI apps",
    ],
  },
  {
    id: "09",
    chapter: "Chapter 9",
    title: "Cloud + Deployment",
    color: "#1A3A5C",
    lessons: 14,
    duration: "2 weeks",
    topics: [
      "Docker & Kubernetes for AI",
      "Serverless inference (Modal, RunPod)",
      "AWS/GCP AI infrastructure",
      "Load balancing & auto-scaling",
      "Capstone project deployment",
    ],
    objectives: [
      "Deploy AI apps to cloud",
      "Scale inference workloads",
      "Ship your capstone to production",
    ],
  },
];

export const WHO_THIS_IS_FOR = [
  {
    title: "Software Engineers",
    description: "Transition from backend or full-stack development into AI engineering with a structured, project-based path.",
    color: "#E85D75",
  },
  {
    title: "Data Scientists",
    description: "Level up from notebooks to production LLM systems, agents, and enterprise-grade AI infrastructure.",
    color: "#7B68A6",
  },
  {
    title: "ML Engineers",
    description: "Bridge the gap between classical ML and modern GenAI with hands-on RAG, agents, and LLMOps.",
    color: "#5BC0BE",
  },
  {
    title: "Tech Leads & Architects",
    description: "Master system design for AI at scale — multi-agent orchestration, guardrails, and cloud deployment.",
    color: "#D4A017",
  },
];

export const WHATS_INCLUDED = [
  { title: "Lifetime Access", description: "All modules, updates, and future content included forever.", icon: "∞", color: "#E85D75" },
  { title: "Hands-on Projects", description: "20+ production-grade projects for your portfolio and interviews.", icon: "⚡", color: "#D4A017" },
  { title: "Community Support", description: "Active Discord community with peers, mentors, and office hours.", icon: "💬", color: "#5BC0BE" },
  { title: "Verified Certificate", description: "Industry-recognized certificate upon completing the full roadmap.", icon: "🎓", color: "#7B68A6" },
];

export const PROJECTS = [
  { title: "RAG-based PDF Chatbot", description: "Build a production chatbot that ingests documents, retrieves context, and answers with citations." },
  { title: "Multi-Agent Research Assistant", description: "Orchestrate agents that search, summarize, and synthesize information autonomously." },
  { title: "AI Code Review Bot", description: "Deploy an agent that reviews pull requests with MCP tool integrations." },
  { title: "Enterprise Knowledge Base", description: "End-to-end system with guardrails, monitoring, and cloud deployment." },
];

export const TRUSTED_COMPANIES = ["Google", "Meta", "Microsoft", "Amazon", "OpenAI", "NVIDIA"];

export const HIGHLIGHTS = [
  { title: "Project-Based Learning", description: "Every module ends with a real-world project you can showcase.", color: "#E85D75" },
  { title: "1-on-1 Mentorship", description: "Book sessions with industry experts for personalized guidance.", color: "#D4A017" },
  { title: "Production-First", description: "Learn patterns used in enterprise AI teams, not just tutorials.", color: "#5BC0BE" },
];

export const MENTOR = {
  name: "Alex Rivera",
  title: "Senior AI Architect",
  company: "Ex-Google, Ex-OpenAI",
  bio: "15+ years building production AI systems at scale. Led teams deploying LLMs serving 100M+ users. Designed RAG pipelines and multi-agent systems for Fortune 500 companies.",
  experience: "10+ Years Experience",
  students: "500+ Students Mentored",
  linkedin: "https://linkedin.com",
  github: "https://github.com",
  twitter: "https://twitter.com",
};

export const COURSES = [
  {
    id: "m-00000000-0000-0000-0000-000000000001",
    slug: "python-ai-foundations",
    title: "Python for AI Foundations",
    short_description: "Master clean object-oriented Python, asynchronous programming patterns, and Pydantic validation for robust LLM applications.",
    thumbnail_url: "/assets/python_essentials_cover.png",
    price: 599,
    originalPrice: 1599,
    discount: "62% OFF",
    difficulty: "Beginner",
    duration_hours: 12,
    tags: ["Python", "AsyncIO", "Pydantic"],
    buyLink: "https://superprofile.bio/vp/ai-engineer--zero-to-production",
  },
  {
    id: "m-00000000-0000-0000-0000-000000000002",
    slug: "advanced-rag-systems",
    title: "Advanced RAG Systems",
    short_description: "Build state-of-the-art Retrieval-Augmented Generation pipelines incorporating hybrid index searches, rerankers, and Ragas metrics.",
    thumbnail_url: "/assets/advanced_rag_cover.png",
    is_free: true,
    price: 0,
    originalPrice: 4999,
    discount: "100% OFF",
    difficulty: "Intermediate",
    duration_hours: 18,
    tags: ["RAG", "Pinecone", "Reranking"],
    buyLink: "https://superprofile.bio/vp/ai-agent-handnotes",
  },
  {
    id: "m-00000000-0000-0000-0000-000000000003",
    slug: "multi-agent-mcp",
    title: "Multi-Agent Orchestration & MCP",
    short_description: "Orchestrate agent teams utilizing Supervisor-worker loops, CrewAI workflows, and tool calling via the Model Context Protocol.",
    thumbnail_url: "/assets/multi_agent_cover.png",
    is_free: true,
    price: 0,
    originalPrice: 4999,
    discount: "100% OFF",
    difficulty: "Advanced",
    duration_hours: 24,
    tags: ["Agents", "MCP", "LangGraph"],
    buyLink: "https://superprofile.bio/vp/ai-agent-handnotes",
  },
  {
    id: "m-00000000-0000-0000-0000-000000000004",
    slug: "llmops-cloud-deployment",
    title: "LLMOps & Cloud Deployment",
    short_description: "Package, evaluate, deploy, and scale large language model servers in Kubernetes with serverless GPU inference providers.",
    thumbnail_url: "/assets/llmops_cover.png",
    is_free: true,
    price: 0,
    originalPrice: 4999,
    discount: "100% OFF",
    difficulty: "Advanced",
    duration_hours: 14,
    tags: ["LLMOps", "Docker", "Modal"],
    buyLink: "https://superprofile.bio/vp/ai-agent-handnotes",
  },
];
